/**
 * What a React Native catalog entry is, and what its rendering entry points
 * receive. Mirrors `@a2ui/react`'s `react_component_implementation.ts`.
 *
 * These types refer to each other: an implementation's `view` takes
 * `NodeViewProps`, which names a node holding an entry of the same catalog.
 * Keeping them together lets `adapter.tsx` build implementations without
 * importing the node layer.
 */

import type {
  ComponentApi,
  ComponentContext,
  ComponentNode,
} from '@a2ui/web_core'
import type React from 'react'
import type { ZodTypeAny } from 'zod'

/** Renders a resolved child node, or falls back for an unresolved id. */
export type NodeBuildChild = (
  child: ComponentNode<ReactComponentImplementation> | string,
  basePath?: string,
) => React.ReactNode

/** What a component implementation's `view` receives from the node surface. */
export type NodeViewProps = {
  node: ComponentNode<ReactComponentImplementation>
  buildChild: NodeBuildChild
}

/** What a React Native implementation's `render` receives. */
export type ReactRenderProps = {
  context: ComponentContext
  buildChild: (id: string, basePath?: string) => React.ReactNode
}

/** A catalog entry implemented as a React Native component. */
export interface ReactComponentImplementation<
  Schema extends ZodTypeAny = ZodTypeAny,
> extends ComponentApi<Schema> {
  /** The framework-specific rendering wrapper. */
  render: React.FC<ReactRenderProps>
  /**
   * Renders this component from a resolved `ComponentNode`. Generated by the
   * factories in `adapter.tsx`. When absent, the surface renders through
   * `render`, handing it a `buildChild` that resolves ids through the node
   * layer.
   */
  view?: React.FC<NodeViewProps>
}

/** What the generic binder hands a presentational React Native component. */
export type ReactA2uiComponentProps<T> = {
  props: T
  buildChild: (id: string, basePath?: string) => React.ReactNode
  context: ComponentContext
}
